// 自动生成：站点清单 + 各站真实搜索URL模板（与 worker/src/search-core.mjs 同步）
// search 模板含 {origin} 与 {kw} 占位符，前端拼出「该站已搜关键词的真实搜索页」，点击即跳。
export const SITES = [
  {
    "id": "sorani",
    "name": "青空次元",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.sorani.net",
    "search": "{origin}/",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "appmovie",
    "name": "APP影院",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.appmovie.art",
    "search": "{origin}/index.php/vod/search.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "auete-video",
    "name": "Auete影视",
    "quality": "蓝光",
    "qualityScore": 4,
    "origin": "https://www.aeete.com",
    "search": "{origin}/auete4so.php?searchword={kw}",
    "captcha": true,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "darkvod",
    "name": "黑夜影院",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://darkvod.com",
    "search": "{origin}/tag/?wd={kw}&submit=",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "nivod",
    "name": "泥视频",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.nivod.vip",
    "search": "{origin}/index.php/vod/search.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "ppnix",
    "name": "PPnix",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.ppnix.com",
    "search": "{origin}/",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "duse91",
    "name": "91毒舌",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.duse0.com",
    "search": "{origin}/search?t=KX6GEEJawvxs4v0NMbRQfQ%3D%3D&k={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "ifn",
    "name": "IFN",
    "quality": "4K",
    "qualityScore": 5,
    "origin": "https://ifn.watch",
    "search": "{origin}/search?q={kw}",
    "captcha": false,
    "ads": true,
    "login": true,
    "pinned": false
  },
  {
    "id": "fdzys",
    "name": "饭搭子影视",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://fdzys.com",
    "search": "{origin}/yu-{kw}-xianguan-de-yingpian-shippin-zhibo",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "sa-video",
    "name": "SA视频",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.lsjys11.com",
    "search": "{origin}/index.php/vod/search.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "juok",
    "name": "剧OK",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://juok3.top",
    "search": "{origin}/search?q={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "yingshidaquan",
    "name": "影视大全",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://yingshidaquan.top",
    "search": "{origin}/index.php/vod/search.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "juzong",
    "name": "剧踪影院",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.juzong01.me",
    "search": "{origin}/vodsearch/{kw}-------------/",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "jianyunys",
    "name": "简云影视",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://jisuzhuiju.com",
    "search": "{origin}/search?keyword={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "pianku",
    "name": "片库",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://4k01.pianku.online",
    "search": "{origin}/vodsearch/-------------.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "66-dapianwang",
    "name": "66 大片网",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.77dpw.vip",
    "search": "{origin}/vodsearch/-------------.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "xhkan",
    "name": "星河影视",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.xhkan.top",
    "search": "{origin}/index.php/vod/search.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "didahd",
    "name": "嘀嗒影视",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.didahd.xyz",
    "search": "{origin}/search/-------------.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "zhuiying",
    "name": "追影",
    "quality": "蓝光",
    "qualityScore": 4,
    "origin": "https://zhuiying3.cc",
    "search": "{origin}/index.php/vod/search.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "wbbb",
    "name": "歪比巴卜",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://wbbb1.com",
    "search": "{origin}/index.php/vod/search.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "kxyy",
    "name": "开心影院",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.kxyy1.cc",
    "search": "{origin}/vodsearch/-------------.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "dhvideo",
    "name": "豆花电影网",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://dhvideo.cc",
    "search": "{origin}/s.html?name={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "zip0",
    "name": "ZIP0",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://zip0.com",
    "search": "{origin}/search?q={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "103-39-111-180-29",
    "name": "可可影视",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.kkys14.com",
    "search": "{origin}/index.php/vod/search.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "sotvla",
    "name": "搜TV啦",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.sotvla.cc",
    "search": "{origin}/search.php?q={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "libvio",
    "name": "LIBVIO",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://libviobd.com",
    "search": "{origin}/index.php/vod/search.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "dbku",
    "name": "独播库",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.dbku.tv",
    "search": "{origin}/vodsearch/-------------.html?wd={kw}",
    "captcha": false,
    "ads": false,
    "login": false,
    "pinned": true
  },
  {
    "id": "yingmao-cangku",
    "name": "影猫仓库",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.ymck.pro",
    "search": "{origin}/search.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "guangsu-yingshi",
    "name": "光速影视",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www.yingshiso.link",
    "search": "{origin}/search.php?searchword={kw}",
    "captcha": true,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "naifei-fyi-19",
    "name": "奈飞工厂",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://naifei.fyi",
    "search": "{origin}/index.php/vod/search.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "zndy",
    "name": "宅男影视",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://zndy.top",
    "search": "{origin}/index.php/vod/search.html?wd={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  },
  {
    "id": "skr-skr1-cc-9",
    "name": "樱之空",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://skr.skr1.cc:666",
    "search": "{origin}/vodsearch/{kw}-------------/",
    "captcha": false,
    "ads": true,
    "login": true,
    "pinned": false
  },
  {
    "id": "aikanbot",
    "name": "爱看机器人",
    "quality": "1080P",
    "qualityScore": 3,
    "origin": "https://www1.aikanbot.com",
    "search": "{origin}/search?q={kw}",
    "captcha": false,
    "ads": true,
    "login": false,
    "pinned": false
  }
];
